# Generated by Django 2.0 on 2017-12-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='altImage',
            field=models.CharField(default='blog post image', max_length=50),
            preserve_default=False,
        ),
    ]
