# Generated by Django 2.0 on 2017-12-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_altimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='altImage',
            field=models.CharField(default='blog post image', max_length=50),
        ),
    ]
